FROM python:3.9.1

RUN apt-get install wget

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY pipeline.py pipeline.py

ENTRYPOINT ["python", "pipeline.py"]